[package]
name = "velocity"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"
lazy_static = "1.4.0"
tokio = { version = "1.34.0", features = ["full"] }  # 确保使用最新版本
meval="0.2.0"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"